name: hungry_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/detail/
    - assets/icon/
    - assets/screens/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Montserrat-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/Montserrat-Bold.ttf
        #   weight: 700
